apiVersion: apps/v1
kind: Deployment
metadata:
  name: ishTestDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ishtest
  template:
    metadata:
      labels:
        app: ishtest
    spec:
      containers:
      - name: ishtest
        image: ishtest
        ports:
        - containerPort: 8000